name: Auto Comment
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            
            To generate the Storybook and Docusaurus websites, write comment with:
            > @eea-jenkins build all
            
            To generate only Storybook write comment with:
            > @eea-jenkins build storybook            
            
            To generate only Docusaurus write comment with:
            > @eea-jenkins build docusaurus  
