# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop-itml ]
  pull_request:
    branches: [ develop ]
    paths:
     - website/**


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js ${{ matrix.node-version }} to build docusaurus website
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Push Docusaurus build changes
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
           cd website
           yarn
           yarn build
           git add . 
           git diff --staged --quiet || git commit -m "Autobuild of docusaurus docs"
           git push
