# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Storybook & Docusaurus CI deployment

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }} to build docusaurus website
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Push Docusaurus build changes
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git fetch
          npx auto-changelog --commit-limit false  --unreleased --stdout  --template templates/eea.hbs > website/docs/2-whatsnew.md
          cd website
          yarn
          yarn build
          cd ..
          git add website docs 
          git commit -m "Autobuild of docusaurus docs"
          git push

    - uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        owner: 'eea'
        repo: 'eea-storybook'
        ref: 'develop'
        workflow_file_name: node.js.yml
    - name: Deploy Storybook changes
      run: |
          echo "Deploy Storybook changes"
          sleep 1s
