# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ github_actions ]
    paths:
     - website/**
  pull_request:
    branches: [ github_actions ]
    paths:
     - website/**
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} to build docusaurus website
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change directory to website
      run: cd website
    - name: Run yarn install
      run: yarn
    - name: Run yarn build
      run: yarn build
    - name: Set git user name
      run: git config user.name github-actions
    - name: Set git user email
      run: git config user.email github-actions@github.com
    - name: Add git changes from docs folder
      run: git add ../docs
    - name: Commit git changes
      run: git diff --staged --quiet || git commit -m "Autobuild of docusaurus docs"
    - name: Push changes
      run: git push
